<template><div><blockquote></blockquote>
<h1 id="cesium调用geoserver服务" tabindex="-1"><a class="header-anchor" href="#cesium调用geoserver服务" aria-hidden="true">#</a> Cesium调用GeoServer服务</h1>
<h2 id="一、使用-webmapserviceimageryprovider-加载服务" tabindex="-1"><a class="header-anchor" href="#一、使用-webmapserviceimageryprovider-加载服务" aria-hidden="true">#</a> 一、使用 WebMapServiceImageryProvider 加载服务</h2>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code>  <span class="token keyword">const</span> tifLayer <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Cesium<span class="token punctuation">.</span>WebMapServiceImageryProvider</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
    <span class="token literal-property property">url</span><span class="token operator">:</span> <span class="token string">'http://192.168.1.1:8080/geoserver/Gansu/wms?service=WMS'</span><span class="token punctuation">,</span>        <span class="token comment">// GeoServer服务地址</span>
    <span class="token literal-property property">layers</span><span class="token operator">:</span> <span class="token string">'Gansu:ten_meter_resolution_land_use_data'</span><span class="token punctuation">,</span>                    <span class="token comment">// 工作空间名:图层名</span>
    <span class="token literal-property property">parameters</span><span class="token operator">:</span> <span class="token punctuation">{</span>
      <span class="token literal-property property">service</span><span class="token operator">:</span> <span class="token string">'WMS'</span><span class="token punctuation">,</span>
      <span class="token literal-property property">format</span><span class="token operator">:</span> <span class="token string">'image/png'</span><span class="token punctuation">,</span>
      <span class="token literal-property property">srs</span><span class="token operator">:</span> <span class="token string">'EPSG:900913'</span><span class="token punctuation">,</span>
      <span class="token comment">// crs: 'EPSG:900913',</span>
      <span class="token literal-property property">transparent</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span>
    <span class="token punctuation">}</span>
  <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

  viewer<span class="token punctuation">.</span>imageryLayers<span class="token punctuation">.</span><span class="token function">addImageryProvider</span><span class="token punctuation">(</span>tifLayer<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="二、添加点击事件获取features" tabindex="-1"><a class="header-anchor" href="#二、添加点击事件获取features" aria-hidden="true">#</a> 二、添加点击事件获取features</h2>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code>  <span class="token keyword">let</span> handler <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Cesium<span class="token punctuation">.</span>ScreenSpaceEventHandler</span><span class="token punctuation">(</span>viewer<span class="token punctuation">.</span>scene<span class="token punctuation">.</span>canvas<span class="token punctuation">)</span><span class="token punctuation">;</span>

  handler<span class="token punctuation">.</span><span class="token function">setInputAction</span><span class="token punctuation">(</span><span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token parameter">movement</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">let</span> cartesian <span class="token operator">=</span> viewer<span class="token punctuation">.</span>camera<span class="token punctuation">.</span><span class="token function">pickEllipsoid</span><span class="token punctuation">(</span>movement<span class="token punctuation">.</span>position<span class="token punctuation">,</span> viewer<span class="token punctuation">.</span>scene<span class="token punctuation">.</span>globe<span class="token punctuation">.</span>ellipsoid<span class="token punctuation">)</span><span class="token punctuation">;</span>

    <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token keyword">typeof</span> cartesian <span class="token operator">===</span> <span class="token string">'undefined'</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
      <span class="token keyword">return</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span>
      <span class="token keyword">let</span> pickRay <span class="token operator">=</span> viewer<span class="token punctuation">.</span>camera<span class="token punctuation">.</span><span class="token function">getPickRay</span><span class="token punctuation">(</span>movement<span class="token punctuation">.</span>position<span class="token punctuation">)</span><span class="token punctuation">;</span>

      viewer<span class="token punctuation">.</span>imageryLayers<span class="token punctuation">.</span><span class="token function">pickImageryLayerFeatures</span><span class="token punctuation">(</span>
        pickRay<span class="token punctuation">,</span>
        viewer<span class="token punctuation">.</span>scene
      <span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">then</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token parameter">feature</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
        <span class="token keyword">if</span> <span class="token punctuation">(</span>feature<span class="token punctuation">)</span> <span class="token punctuation">{</span>
          <span class="token keyword">let</span> cartographic <span class="token operator">=</span> Cesium<span class="token punctuation">.</span>Cartographic<span class="token punctuation">.</span><span class="token function">fromCartesian</span><span class="token punctuation">(</span>cartesian<span class="token punctuation">)</span><span class="token punctuation">;</span>

          <span class="token keyword">let</span> lon <span class="token operator">=</span> Cesium<span class="token punctuation">.</span>Math<span class="token punctuation">.</span><span class="token function">toDegrees</span><span class="token punctuation">(</span>cartographic<span class="token punctuation">.</span>longitude<span class="token punctuation">)</span><span class="token punctuation">;</span>
          <span class="token keyword">let</span> lat <span class="token operator">=</span> Cesium<span class="token punctuation">.</span>Math<span class="token punctuation">.</span><span class="token function">toDegrees</span><span class="token punctuation">(</span>cartographic<span class="token punctuation">.</span>latitude<span class="token punctuation">)</span><span class="token punctuation">;</span>

          <span class="token keyword">let</span> data <span class="token operator">=</span> feature<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">.</span>data<span class="token punctuation">;</span>

          console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>data<span class="token punctuation">.</span>properties<span class="token punctuation">)</span>
        <span class="token punctuation">}</span>
      <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>

  <span class="token punctuation">}</span><span class="token punctuation">,</span> Cesium<span class="token punctuation">.</span>ScreenSpaceEventType<span class="token punctuation">.</span><span class="token constant">LEFT_CLICK</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="二、通过geoserver服务查询features" tabindex="-1"><a class="header-anchor" href="#二、通过geoserver服务查询features" aria-hidden="true">#</a> 二、通过GeoServer服务查询features</h2>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">function</span> <span class="token function">getUrlLayerInfoByCoor</span><span class="token punctuation">(</span><span class="token parameter">lon<span class="token punctuation">,</span> lat<span class="token punctuation">,</span> vm</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
  <span class="token keyword">return</span> <span class="token keyword">new</span> <span class="token class-name">Promise</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token parameter">resolve<span class="token punctuation">,</span> reject</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
    <span class="token keyword">var</span> pointA <span class="token operator">=</span> turf<span class="token punctuation">.</span><span class="token function">point</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token number">96.049959</span><span class="token punctuation">,</span> <span class="token number">40.177626</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token comment">// var pointA = turf.point([parseFloat(lon), parseFloat(lat)]);</span>
    <span class="token keyword">var</span> pointB <span class="token operator">=</span> turf<span class="token punctuation">.</span><span class="token function">destination</span><span class="token punctuation">(</span>pointA<span class="token punctuation">,</span> <span class="token number">50</span><span class="token punctuation">,</span> <span class="token number">45</span><span class="token punctuation">,</span> <span class="token punctuation">{</span> <span class="token literal-property property">units</span><span class="token operator">:</span> <span class="token string">'meters'</span> <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//kilometers</span>
    <span class="token keyword">var</span> bbx <span class="token operator">=</span> turf<span class="token punctuation">.</span><span class="token function">bbox</span><span class="token punctuation">(</span>turf<span class="token punctuation">.</span><span class="token function">featureCollection</span><span class="token punctuation">(</span><span class="token punctuation">[</span>pointA<span class="token punctuation">,</span> pointB<span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>  <span class="token comment">//经纬度转四至</span>

    <span class="token comment">// 经纬度转墨卡托</span>
    <span class="token keyword">let</span> box_a <span class="token operator">=</span> <span class="token function">lonLatToMercator</span><span class="token punctuation">(</span>bbx<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">,</span> bbx<span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">]</span><span class="token punctuation">)</span>
    <span class="token keyword">let</span> box_b <span class="token operator">=</span> <span class="token function">lonLatToMercator</span><span class="token punctuation">(</span>bbx<span class="token punctuation">[</span><span class="token number">2</span><span class="token punctuation">]</span><span class="token punctuation">,</span> bbx<span class="token punctuation">[</span><span class="token number">3</span><span class="token punctuation">]</span><span class="token punctuation">)</span>

    <span class="token keyword">let</span> url <span class="token operator">=</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">http://192.168.1.1:8080/geoserver/Gansu/wms?SERVICE=WMS
  &amp;VERSION=1.1.1
  &amp;REQUEST=GetFeatureInfo
  &amp;FORMAT=image/jpeg
  &amp;TRANSPARENT=true
  &amp;QUERY_LAYERS=Gansu:Jiuquan_ten_meter_resolution_land_use_data
  &amp;STYLES=&amp;LAYERS=Gansu:Jiuquan_ten_meter_resolution_land_use_data
  &amp;exceptions=application/vnd.ogc.se_inimage
  &amp;INFO_FORMAT=application/json
  &amp;FEATURE_COUNT=50
  &amp;X=50&amp;Y=50
  &amp;SRS=EPSG:3857
  &amp;WIDTH=101
  &amp;HEIGHT=101
  &amp;BBOX=</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>box_a<span class="token punctuation">.</span>x<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">,</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>box_a<span class="token punctuation">.</span>y<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">,</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>box_b<span class="token punctuation">.</span>x<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">,</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>box_b<span class="token punctuation">.</span>y<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span>

    <span class="token function">fetch</span><span class="token punctuation">(</span>url<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">then</span><span class="token punctuation">(</span><span class="token parameter">res</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
      <span class="token keyword">return</span> res<span class="token punctuation">.</span><span class="token function">json</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">then</span><span class="token punctuation">(</span><span class="token parameter">res</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
      <span class="token keyword">let</span> features <span class="token operator">=</span> res<span class="token punctuation">.</span>features<span class="token punctuation">;</span>
      <span class="token keyword">if</span> <span class="token punctuation">(</span>features<span class="token punctuation">.</span>length<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">let</span> data <span class="token operator">=</span> features<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">;</span>

        <span class="token function">resolve</span><span class="token punctuation">(</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span>
      <span class="token punctuation">}</span>
    <span class="token punctuation">}</span><span class="token punctuation">)</span>
  <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>

</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token comment">//经纬度转墨卡托</span>
<span class="token keyword">function</span> <span class="token function">lonLatToMercator</span><span class="token punctuation">(</span><span class="token parameter">lon<span class="token punctuation">,</span> lat</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
  <span class="token keyword">let</span> mercator <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token punctuation">}</span><span class="token punctuation">;</span>
  <span class="token keyword">let</span> earthRad <span class="token operator">=</span> <span class="token number">6378137.0</span><span class="token punctuation">;</span>
  mercator<span class="token punctuation">.</span>x <span class="token operator">=</span> lon <span class="token operator">*</span> Math<span class="token punctuation">.</span><span class="token constant">PI</span> <span class="token operator">/</span> <span class="token number">180</span> <span class="token operator">*</span> earthRad<span class="token punctuation">;</span>

  <span class="token keyword">let</span> a <span class="token operator">=</span> lat <span class="token operator">*</span> Math<span class="token punctuation">.</span><span class="token constant">PI</span> <span class="token operator">/</span> <span class="token number">180</span><span class="token punctuation">;</span>
  mercator<span class="token punctuation">.</span>y <span class="token operator">=</span> earthRad <span class="token operator">/</span> <span class="token number">2</span> <span class="token operator">*</span> Math<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token number">1.0</span> <span class="token operator">+</span> Math<span class="token punctuation">.</span><span class="token function">sin</span><span class="token punctuation">(</span>a<span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token operator">/</span> <span class="token punctuation">(</span><span class="token number">1.0</span> <span class="token operator">-</span> Math<span class="token punctuation">.</span><span class="token function">sin</span><span class="token punctuation">(</span>a<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

  <span class="token keyword">return</span> mercator<span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


